[package]
name = "picnic-bindings"
description = "Bindings for the Picnic digital signature scheme"
version = "0.2.0"
authors = ["Sebastian Ramacher <sebastian.ramacher@ait.ac.at>"]
homepage = "https://microsoft.github.io/Picnic/"
repository = "https://github.com/ait-crypto/picnic-bindings-rs"
license = "MIT"
edition = "2018"
keywords = ["signatures", "Picnic"]
categories = ["cryptography", "api-bindings"]

[dependencies]
picnic-sys = { version = "3.0.4", path = "picnic-sys", default-features = false }
signature = "1.3"

[dev-dependencies]
generic-tests = "0.1"

[workspace]
members = ["picnic-sys"]

[features]
default = ["system", "static-fallback", "picnic", "picnic3"]
picnic = ["picnic-sys/picnic"]
picnic3 = ["picnic-sys/picnic3"]
unruh-transform = ["picnic-sys/unruh-transform"]
system = ["picnic-sys/system"]
static-fallback = ["picnic-sys/static-fallback"]

[package.metadata.docs.rs]
all-features = true