[package]
name = "picnic-sys"
description = "Declarations for using Picinc's shared library"
version = "3.0.3"
authors = ["Sebastian Ramacher <sebastian.ramacher@ait.ac.at>"]
homepage = "https://microsoft.github.io/Picnic/"
repository = "https://github.com/ait-crypto/picnic-bindings-rs"
license = "MIT"
edition = "2018"
links = "picnic"
categories = ["external-ffi-bindings"]
exclude = ["Picnic/tests"]

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = {version = "0.3", optional = true}
cc = {version = "1", optional = true, features = ["parallel"]}

[features]
default = ["system", "static-fallback", "picnic", "picnic3"]
picnic = []
picnic3 = []
unruh-transform = ["picnic"]
system = ["pkg-config"]
static-fallback = ["cc"]
docs-rs = []

[package.metadata.docs.rs]
features = ["docs-rs"]