[package]
name = "picnic-sys"
description = "Declarations for using Picnic's shared library"
version = "3.0.14"
authors = ["Sebastian Ramacher <sebastian.ramacher@ait.ac.at>"]
homepage = "https://microsoft.github.io/Picnic/"
repository = "https://github.com/ait-crypto/picnic-bindings-rs"
license = "MIT"
edition = "2021"
rust-version = "1.56"
links = "picnic"
categories = ["external-ffi-bindings"]

[dependencies]
libc = { version = "0.2", default-features = false }

[build-dependencies]
pkg-config = { version = "0.3", optional = true }
cc = { version = "1", optional = true, features = ["parallel"] }

[dev-dependencies]
hex = "0.4"

[features]
default = ["system", "static-fallback", "picnic", "picnic3"]
picnic = []
picnic3 = []
unruh-transform = ["picnic"]
system = ["pkg-config"]
static-fallback = ["cc"]
