name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-shared:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    name: Test w. shared library (${{matrix.toolchain}} toolchain)
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install dependencies
        run: |
          sudo add-apt-repository -u -y ppa:s-ramacher/picnic
          sudo apt install libpicnic-dev pkg-config
      - name: Test with default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
      - name: Test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  test-static:
    needs: [test-shared, clippy, fmt]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: Test w. static-fallback (${{matrix.toolchain}} toolchain, ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Test with default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
      - name: Test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  build-cross:
    needs: test-static
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu
          - mips64el-unknown-linux-gnuabi64
          - powerpc64le-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          # - arm-linux-androideabi
    name: Cross test for ${{matrix.target}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{matrix.target}}
      - uses: Swatinem/rust-cache@v1
      - name: Test with default features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --workspace --target ${{matrix.target}}
      - name: Test with all features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --all-features --target ${{matrix.target}}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Install dependencies
        run: |
          sudo add-apt-repository -u -y ppa:s-ramacher/picnic
          sudo apt install libpicnic-dev pkg-config
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
